<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Taking Stats by the Helm</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="A Forum for Understanding Statistics">
  <meta name="generator" content="bookdown 0.1 and GitBook 2.6.7">

  <meta property="og:title" content="Taking Stats by the Helm" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A Forum for Understanding Statistics" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Taking Stats by the Helm" />
  
  <meta name="twitter:description" content="A Forum for Understanding Statistics" />
  

<meta name="author" content="Jonathan Lee Helm">


<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="notation.html">
<link rel="next" href="anova.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Forum for Understanding Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome</a></li>
<li class="chapter" data-level="2" data-path="notation.html"><a href="notation.html"><i class="fa fa-check"></i><b>2</b> Notation</a></li>
<li class="chapter" data-level="3" data-path="t-tests.html"><a href="t-tests.html"><i class="fa fa-check"></i><b>3</b> <em>t</em>-tests</a><ul>
<li class="chapter" data-level="3.1" data-path="t-tests.html"><a href="t-tests.html#null-and-alternative-hypotheses-for-t-tests"><i class="fa fa-check"></i><b>3.1</b> Null and Alternative Hypotheses for <em>t</em>-Tests</a></li>
<li class="chapter" data-level="3.2" data-path="t-tests.html"><a href="t-tests.html#from-the-population-to-the-sample"><i class="fa fa-check"></i><b>3.2</b> From the Population to the Sample</a></li>
<li class="chapter" data-level="3.3" data-path="t-tests.html"><a href="t-tests.html#applying-the-concepts-of-the-z-distribution"><i class="fa fa-check"></i><b>3.3</b> Applying the Concepts of the <em>z</em>-distribution</a></li>
<li class="chapter" data-level="3.4" data-path="t-tests.html"><a href="t-tests.html#what-is-a-t-test"><i class="fa fa-check"></i><b>3.4</b> What is a <em>t</em>-test?</a></li>
<li class="chapter" data-level="3.5" data-path="t-tests.html"><a href="t-tests.html#what-are-the-different-types-of-t-tests"><i class="fa fa-check"></i><b>3.5</b> What are the different types of <em>t</em>-tests?</a></li>
<li class="chapter" data-level="3.6" data-path="t-tests.html"><a href="t-tests.html#independent-samples-t-tests"><i class="fa fa-check"></i><b>3.6</b> Independent samples <em>t</em>-tests</a><ul>
<li class="chapter" data-level="3.6.1" data-path="t-tests.html"><a href="t-tests.html#an-example-in-r"><i class="fa fa-check"></i><b>3.6.1</b> An example in R</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="t-tests.html"><a href="t-tests.html#dependent-samples-t-tests"><i class="fa fa-check"></i><b>3.7</b> Dependent samples <em>t</em>-tests</a><ul>
<li class="chapter" data-level="3.7.1" data-path="t-tests.html"><a href="t-tests.html#an-example-in-r-1"><i class="fa fa-check"></i><b>3.7.1</b> An example in R</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="anova.html"><a href="anova.html"><i class="fa fa-check"></i><b>4</b> ANOVA</a></li>
<li class="chapter" data-level="5" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>5</b> Regression</a></li>
<li class="chapter" data-level="6" data-path="multilevel-models.html"><a href="multilevel-models.html"><i class="fa fa-check"></i><b>6</b> Multilevel Models</a></li>
<li class="chapter" data-level="7" data-path="structural-equation-models.html"><a href="structural-equation-models.html"><i class="fa fa-check"></i><b>7</b> Structural Equation Models</a></li>
<li class="divider"></li>
<li><a href="https://TakingStatsByTheHelm.github.io/site" target="blank">Maintained by Jonathan Lee Helm</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Taking Stats by the Helm</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="t-tests" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> <em>t</em>-tests</h1>
<p>In general, <em>t</em>-tests determine whether the average of some variable differs <strong><em>significantly</em></strong> across two groups. For example, a <em>t</em>-test may be used to answer questions such as ‘Are women more intelligent than men?’, ‘Do younger individuals tend to be more extraverted compared to older individuals?’, or ‘Do those with college degrees earn more money than those without college degrees?’. For each of these examples we have two different groups (i.e., women vs. men, young vs. old, those with undergraduate degrees vs. those without), and we are comparing them on some variable of interest (i.e., intelligence, extraversion, or income).</p>
<div id="null-and-alternative-hypotheses-for-t-tests" class="section level2">
<h2><span class="header-section-number">3.1</span> Null and Alternative Hypotheses for <em>t</em>-Tests</h2>
<p>Let’s consider the third example in more detail (‘Do those with college degrees earn more money than those without college degrees?’). Let’s begin by forming a null and alternative hypothesis to guide our analysis of the data.</p>
<p><strong>Null Hypothesis</strong>: Those with college degrees earn the same amount of money as those without college degrees. This can also be written as <span class="math inline">\(\mu_{college} = \mu_{no\ college}\)</span>.</p>
<p><strong>Alternative hypothesis</strong>: Those with college degress do not earn the same amount of money as those without college degrees. This can also be written as <span class="math inline">\(\mu_{college} \neq \mu_{no\ college}\)</span>.</p>
<p>In an ideal world we would directly compare the means across the groups. For example, if we wanted to compare salaries across college graduates versus non college graduates, then we would collect salary information for <em>all</em> college graduaes and non college graduates, compute means salaries for each group, calculate the difference between the group means, and use the difference to decide whether there is a difference between college graduates’ and non college graduates’ salaries.</p>
<p>Of course, direct comparison is rarely possible. Researchers typically do not have enough time or money to collect data from every member of the population (e.g., collecting salary information across college graduates and non college graduates). Therefore, we need an indirect method for comparing mean differences between groups. Typically, a researcher will collect a <strong><em>sample</em></strong> of individuals from the population, and hope to make comparisons about the populations of interest using these samples.</p>
</div>
<div id="from-the-population-to-the-sample" class="section level2">
<h2><span class="header-section-number">3.2</span> From the Population to the Sample</h2>
<p>Within the null and alternative hypotheses, <span class="math inline">\(\mu_{college}\)</span> refers to the average amount of money made across all individuals <em>with</em> an undergraduate degree, and <span class="math inline">\(\mu_{no\ college}\)</span> reflects the average amount of money made across all individuals <em>without</em> an undergraduate degree. Therefore, if we had measurements from all individuals within the population, we would be able to evaluate the null and alternative hypotheses directly (i.e., we would just compare <span class="math inline">\(\mu_{college}\)</span> to <span class="math inline">\(\mu_{no\ college}\)</span>).</p>
<p>Instead, we only have estimates of <span class="math inline">\(\mu_{college}\)</span> and <span class="math inline">\(\mu_{no\ college}\)</span>, and these estimates are calculated directly from our sample data. In the case of a <em>t</em>-test, we use the sample mean to estimate <span class="math inline">\(\mu\)</span>. More specifically (and following the example based on salary and college education status), we calculate <span class="math inline">\(\bar{X}\)</span> as an estimate of <span class="math inline">\(\mu\)</span> (i.e., we use <span class="math inline">\(\bar{X}_{college}\)</span> and <span class="math inline">\(\bar{X}_{no\ college}\)</span> to estimate <span class="math inline">\(\mu_{college}\)</span> to <span class="math inline">\(\mu_{no\ college}\)</span>, respectively).</p>
<p>One may believe that a simple difference between the two sample means <span class="math inline">\(\bar{X}_{college}\)</span> and <span class="math inline">\(\bar{X}_{no\ college}\)</span> would provide an answer to our original question. However, that difference only refers only to the difference between a subset (i.e., a sample) of the population, and we may not be certain that such a difference would generalize. Let’s emphasize this notion using an experience from a first year graduate student named Julie.</p>
<p>Julie decides to collect a sample from the population (<em>N</em> = 100, with 50 individuals with college degrees and 50 indiviudals without college degrees), and finds that the difference between the respective sample means equals $20. Then, Julie decides that there isn’t a large difference in salary across college graduates and non college graduates.</p>
<p>But Julie’s classmate, Jill, asks Julie if the finding would replicate. More specifically, Jill wonders whether the $20 difference would occur within another sample (indicating that the small difference generalizes across samples, and therefore describes the population), or if the difference would be largely different within a second sample (indicating that the difference of $20 only characterizes the first sample, and not the population).</p>
<p>Julie - who hasn’t studied <em>t</em>-tests yet - decides to collect another sample in order to answer Jill’s question. But, prior to collecting the second sample, Julie imagines Jill asking whether the results would replicate a third or fourth time. Therefore, Julie decides to collect 5 samples to answer Jill’s question more thoroughly.</p>
<p>Now, before we discuss what Jill found, let’s imagine two different scenarios. Within ‘Scenario 1’, there really is no difference between the salaries of college graduates and non college graduates (i.e., the null hypothesis is true), and Julie’s first sample actually does provide good insight into what occurs across the population. Within ‘Scenario 2’, there really is a difference in salaries across the two groups (i.e., the alternative hypothesis is true), and the small difference of $20 observed within Julie’s first sample was just a fluke. We play out Scenarios 1 and 2 within the table below.</p>
<table style="width:71%;">
<colgroup>
<col width="23%" />
<col width="23%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th>Sample Number</th>
<th>Scenario 1 <span class="math inline">\(\bar{X}_{college} - \bar{X}_{no\ college}\)</span></th>
<th>Scenario 2 <span class="math inline">\(\bar{X}_{college} - \bar{X}_{no\ college}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>20</td>
<td>20</td>
</tr>
<tr class="even">
<td>2</td>
<td>-15</td>
<td>19,000</td>
</tr>
<tr class="odd">
<td>3</td>
<td>10</td>
<td>30,000</td>
</tr>
<tr class="even">
<td>4</td>
<td>2</td>
<td>23,500</td>
</tr>
<tr class="odd">
<td>5</td>
<td>-16</td>
<td>24,000</td>
</tr>
<tr class="even">
<td>6</td>
<td>4</td>
<td>28,000</td>
</tr>
<tr class="odd">
<td>7</td>
<td>-3</td>
<td>27,000</td>
</tr>
<tr class="even">
<td>8</td>
<td>-11</td>
<td>28,225</td>
</tr>
<tr class="odd">
<td>9</td>
<td>10</td>
<td>25,500</td>
</tr>
<tr class="even">
<td>10</td>
<td>5</td>
<td>26,000</td>
</tr>
</tbody>
</table>
<p>Within Scenario 1, Julie tells Jill that she is more confident that the results will generalize to the popuation given that all 5 samples produced a relatively trivial mean difference across annual salaries. And, within Scenario 2, Julie is perhaps, more convinced that there is meaningful difference across annual salaries. Needless to say, if Julie hadn’t produced the extra samples, it would be difficult to determine whether the sample mean difference (i.e., <span class="math inline">\(\bar{X}_{college} - \bar{X}_{no\ college}\)</span>) would generalize across samples. However, the main limitation of Julie’s approach is the need to collect multiple samples from the population.</p>
</div>
<div id="applying-the-concepts-of-the-z-distribution" class="section level2">
<h2><span class="header-section-number">3.3</span> Applying the Concepts of the <em>z</em>-distribution</h2>
<p>As we continue with the example from Julie, we note that it would be informative to compute the probability that the null hypothesis is true for Scenario 1 (or 2). Stated differently, given that we observed the sample mean differences in Scenario 1 (or 2), what is the probability that <span class="math inline">\(\mu_{college} = \mu_{no\ college}\)</span>? If the probability is very small, say less than .05, then we may use it as justification for rejecting the the null hypothesis and concluding the alternative.</p>
<p>But how can we go about computing that information?</p>
<p>First, remember that <em>z</em>-distributions enable us to calculate probabilities of specific observations. If we assume that the <span class="math inline">\(\bar{X}_{college} - \bar{X}_{no\ college}\)</span> follow a normal distribution, then we can convert use the <em>z</em>-distribution to estimate the probability that the null hypothesis is true.</p>
<p>Let us use R to calculate the means and standard deviations for Scenarios 1 and 2.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">### Make a data set that contains both scenarios. Normally we would read this data set into R, but
### since it is so small, we will just enter it manually here.

data =<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">sample     =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">10</span>),
                  <span class="dt">scenario_1 =</span> <span class="kw">c</span>(<span class="dv">20</span>, -<span class="dv">15</span>, <span class="dv">10</span>, <span class="dv">2</span>, -<span class="dv">16</span>, <span class="dv">4</span>, -<span class="dv">3</span>, -<span class="dv">11</span>, <span class="dv">10</span>, <span class="dv">5</span>),
                  <span class="dt">scenario_2 =</span> <span class="kw">c</span>(<span class="dv">20</span>, <span class="dv">19000</span>, <span class="dv">30000</span>, <span class="dv">23500</span>, <span class="dv">24000</span>, <span class="dv">28000</span>, <span class="dv">27000</span>, <span class="dv">28225</span>, <span class="dv">25500</span>, <span class="dv">26000</span>))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">### Calculating the mean and standard deviation for Scenario 1
<span class="kw">mean</span>(data$scenario_1)</code></pre></div>
<pre><code>## [1] 0.6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(data$scenario_1)</code></pre></div>
<pre><code>## [1] 11.79642</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">### Calculating the mean and standard deviation for Scenario 2
<span class="kw">mean</span>(data$scenario_2)</code></pre></div>
<pre><code>## [1] 23124.5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(data$scenario_2)</code></pre></div>
<pre><code>## [1] 8677.724</code></pre>
<p>Therefore, the mean of and standard deviation of Scenario 1 equal 0.6 and 11.80, respectively (with some rounding). And, the mean and standard deviation of Scenario 2 equal 23124.5 and 8677.72.</p>
</div>
<div id="what-is-a-t-test" class="section level2">
<h2><span class="header-section-number">3.4</span> What is a <em>t</em>-test?</h2>
<p>Often researchers want to compare respones from two different groups. Perhaps the simplest comparison a scientist can make is the difference between two A <em>t</em>-test is a statistical analysis that tests for mean differences between <em>two</em> groups.</p>
</div>
<div id="what-are-the-different-types-of-t-tests" class="section level2">
<h2><span class="header-section-number">3.5</span> What are the different types of <em>t</em>-tests?</h2>
<p>There are two types of <em>t</em>-tests: indepenent samples <em>t</em>-test and dependent samples <em>t</em>-tests. Independent samples <em>t</em>-tests are reserved for</p>
</div>
<div id="independent-samples-t-tests" class="section level2">
<h2><span class="header-section-number">3.6</span> Independent samples <em>t</em>-tests</h2>
<div id="an-example-in-r" class="section level3">
<h3><span class="header-section-number">3.6.1</span> An example in R</h3>
</div>
</div>
<div id="dependent-samples-t-tests" class="section level2">
<h2><span class="header-section-number">3.7</span> Dependent samples <em>t</em>-tests</h2>
<div id="an-example-in-r-1" class="section level3">
<h3><span class="header-section-number">3.7.1</span> An example in R</h3>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="notation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="anova.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://TakingStatsByTheHelm.github.io/site02-t-tests.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
